/**
 * One renderer per CI platform, all reading the same `GateModel`.
 *
 * Every renderer's step translation is an exhaustive `switch` over `GateStep`
 * with no default branch, so adding a step to the shared model does not
 * compile until all seven platforms have said what they do with it. That is
 * the mechanism behind spec 0019 Requirement 2.2 — one edit propagating rather
 * than seven files that happen to agree today.
 *
 * Two deliveries exist, and the difference is whether checkyourvibe can put the
 * gate somewhere the platform will find it without editing structure it cannot
 * safely parse:
 *
 * - `file` — the platform reads more than one config file, so a dedicated file
 *   is written (GitHub Actions, Azure Pipelines), or the config format has a
 *   top-level namespace a job can be appended to (GitLab CI).
 * - `manual` — the platform reads exactly one file and the gate has to nest
 *   inside an existing key (`jobs:`, `pipelines:`, a Groovy `stages { }`).
 *   Appending a top-level block there produces a duplicate key or a parse
 *   error, so the snippet is printed and nothing is written. This is the same
 *   refusal `cyv install-hooks` makes when it finds a pre-commit hook it does
 *   not recognise: printing the command beats guessing at someone's file.
 */
import { join } from 'node:path';
import type { PlannedWrite } from '../protocol/index.js';
import type { CiSystemId } from './detect.js';
import { CI_SYSTEM_NAMES } from './detect.js';
import type { GateModel, GateStep } from './model.js';

export type GateDelivery = 'file' | 'manual';

export interface CiGate {
  system: CiSystemId;
  name: string;
  delivery: GateDelivery;
  /** The write to plan, for `file` delivery. Absent for `manual`. */
  write: PlannedWrite | undefined;
  /** The rendered gate: the file body for `file`, the text to paste for `manual`. */
  snippet: string;
  /** Why nothing is written. Present only for `manual`. */
  manualReason: string | undefined;
  /** What the user still has to do after this lands, if anything. */
  followUp: string[];
}

const BLOCK_ID_PREFIX = 'ci-';

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.length === 0 ? line : `${pad}${line}`))
    .join('\n');
}

/**
 * What every rendered gate says about itself before it says anything a runner
 * acts on.
 *
 * Spec 0019 Requirement 6.4 asks for the verification limit to be stated in the
 * generated output rather than only in documentation the reader may never open.
 * This project maintains no account or runner on any of these platforms.
 *
 * The two deliveries get different wording because they are different objects:
 * a written file has markers and can be refreshed by re-running the command; a
 * printed snippet has neither, and saying it does would send a reader looking
 * for a block that is not in their file.
 */
function header(
  system: CiSystemId,
  delivery: GateDelivery,
  /** What checkyourvibe's own tests can parse this output as, if anything. */
  parsedAs: 'yaml' | 'nothing',
  invocationNote: string[],
): string[] {
  const platform = CI_SYSTEM_NAMES[system];
  const lines =
    delivery === 'file'
      ? [
          'Generated by `cyv install-ci`.',
          '',
          'Re-running that command rewrites the region between the checkyourvibe',
          'markers and leaves everything outside them byte-for-byte alone.',
          '',
        ]
      : ['Rendered by `cyv install-ci` to be added by hand. Nothing was written.', ''];

  lines.push(`checkyourvibe maintains no account and no runner on ${platform}.`);
  lines.push(
    ...(parsedAs === 'yaml'
      ? [
          'This is checked as YAML by checkyourvibe\'s own test suite, and no further:',
          `it has not been executed on ${platform} by this project.`,
        ]
      : [
          'Groovy is not a format checkyourvibe parses, so this is not checked by its',
          `test suite either, and it has not been executed on ${platform} by this project.`,
        ]),
  );

  if (invocationNote.length > 0) {
    lines.push('', ...invocationNote);
  }

  return lines;
}

/**
 * The comment a pipeline carries when the repository does not declare
 * checkyourvibe as a dependency.
 *
 * The generated file names a bare `cyv` in that case, and nothing in the
 * pipeline installs it. Saying so in the file is the difference between a
 * pipeline that fails on its first run with a reason attached and one that
 * fails with `cyv: command not found`.
 */
function invocationNote(model: GateModel): string[] {
  if (model.invocation.resolvedFromDependency) {
    return [];
  }
  return [
    'This repository does not declare checkyourvibe as a dependency, so the gate',
    'below invokes a bare `cyv` that nothing in this pipeline installs. Add',
    'checkyourvibe to the project\'s dependencies and re-run `cyv install-ci`, or',
    'add a step here that puts `cyv` on PATH. Until one of those happens this job',
    'fails with "cyv: command not found" rather than checking anything.',
  ];
}

function commentBlock(lines: string[], prefix: string): string {
  return lines.map((line) => (line.length === 0 ? prefix.trimEnd() : `${prefix}${line}`)).join('\n');
}

function hashComment(lines: string[]): string {
  return commentBlock(lines, '# ');
}

function slashComment(lines: string[]): string {
  return commentBlock(lines, '// ');
}

/** The reason full history is requested, repeated wherever a platform expresses it. */
const FETCH_DEPTH_COMMENT = [
  'Full history. The gate runs --all, which needs no merge base, but a shallow',
  'clone is what empties a diff-scoped run without changing its exit code, so',
  'this file does not leave that set for whoever narrows the mode later.',
];

/** `FETCH_DEPTH_COMMENT` as `#` comment lines at a given indent. */
function fetchDepthComment(spaces: number): string[] {
  const pad = ' '.repeat(spaces);
  return FETCH_DEPTH_COMMENT.map((line) => `${pad}# ${line}`);
}

function githubSteps(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    lines.push(...githubStep(step));
  }

  return lines;
}

function githubStep(step: GateStep): string[] {
  switch (step.kind) {
    case 'checkout':
      return [
        '- name: Checkout',
        '  uses: actions/checkout@v4',
        '  with:',
        ...fetchDepthComment(4),
        `    fetch-depth: ${step.fetchDepth}`,
      ];
    case 'setup-node':
      return [
        '- name: Set up Node',
        '  uses: actions/setup-node@v4',
        '  with:',
        `    node-version: '${step.version}'`,
      ];
    case 'enable-corepack':
      return ['- name: Enable corepack', '  run: corepack enable'];
    case 'install-dependencies':
      return ['- name: Install dependencies', `  run: ${step.command}`];
    case 'run-gate':
      return ['- name: checkyourvibe', '  run: |', indent(step.script, 4)];
  }
}

function renderGithubActions(repoRoot: string, model: GateModel): CiGate {
  const body = [
    hashComment(header('github-actions', 'file', 'yaml', invocationNote(model))),
    '',
    'name: checkyourvibe',
    '',
    'on:',
    '  push:',
    '  pull_request:',
    '',
    'jobs:',
    '  checkyourvibe:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    indent(githubSteps(model).join('\n'), 6),
  ].join('\n');

  return {
    system: 'github-actions',
    name: CI_SYSTEM_NAMES['github-actions'],
    delivery: 'file',
    write: {
      path: join(repoRoot, '.github', 'workflows', 'checkyourvibe.yml'),
      strategy: 'managed-block',
      blockId: `${BLOCK_ID_PREFIX}github-actions`,
      blockComment: 'hash',
      content: body,
      description:
        'Add a GitHub Actions workflow that fails the build on any error-severity violation.',
    },
    snippet: body,
    manualReason: undefined,
    followUp: [],
  };
}

function gitlabScriptEntries(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    switch (step.kind) {
      case 'checkout':
        // GitLab clones the repository itself; depth is a variable, not a step.
        break;
      case 'setup-node':
        // Expressed as the job's `image:`, below, rather than as a script line.
        break;
      case 'enable-corepack':
        lines.push('- corepack enable');
        break;
      case 'install-dependencies':
        lines.push(`- ${step.command}`);
        break;
      case 'run-gate':
        lines.push('- |', indent(step.script, 2));
        break;
    }
  }

  return lines;
}

function nodeVersionOf(model: GateModel): string {
  for (const step of model.steps) {
    if (step.kind === 'setup-node') {
      return step.version;
    }
  }
  return 'lts';
}

function fetchDepthOf(model: GateModel): number {
  for (const step of model.steps) {
    if (step.kind === 'checkout') {
      return step.fetchDepth;
    }
  }
  return 0;
}

function renderGitlabCi(repoRoot: string, model: GateModel): CiGate {
  const body = [
    hashComment(header('gitlab-ci', 'file', 'yaml', invocationNote(model))),
    '#',
    '# This job declares no `stage:`, so GitLab places it in the built-in `test`',
    '# stage. A pipeline that defines its own `stages:` without a `test` entry',
    '# will reject it — add a `stage:` line naming one of yours.',
    'checkyourvibe:',
    `  image: node:${nodeVersionOf(model)}`,
    '  variables:',
    ...fetchDepthComment(4),
    `    GIT_DEPTH: "${fetchDepthOf(model)}"`,
    '  script:',
    indent(gitlabScriptEntries(model).join('\n'), 4),
  ].join('\n');

  return {
    system: 'gitlab-ci',
    name: CI_SYSTEM_NAMES['gitlab-ci'],
    delivery: 'file',
    write: {
      path: join(repoRoot, '.gitlab-ci.yml'),
      strategy: 'managed-block',
      blockId: `${BLOCK_ID_PREFIX}gitlab`,
      blockComment: 'hash',
      content: body,
      description:
        'Append a checkyourvibe job to .gitlab-ci.yml inside a managed block; everything already in the file is preserved.',
    },
    snippet: body,
    manualReason: undefined,
    followUp: [],
  };
}

function azureSteps(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    switch (step.kind) {
      case 'checkout':
        lines.push('- checkout: self', ...fetchDepthComment(2), `  fetchDepth: ${step.fetchDepth}`);
        break;
      case 'setup-node':
        lines.push(
          '- task: NodeTool@0',
          '  displayName: Set up Node',
          '  inputs:',
          `    versionSpec: '${step.version}.x'`,
        );
        break;
      case 'enable-corepack':
        lines.push('- script: corepack enable', '  displayName: Enable corepack');
        break;
      case 'install-dependencies':
        lines.push(`- script: ${step.command}`, '  displayName: Install dependencies');
        break;
      case 'run-gate':
        lines.push('- script: |', indent(step.script, 4), '  displayName: checkyourvibe');
        break;
    }
  }

  return lines;
}

function renderAzurePipelines(repoRoot: string, model: GateModel): CiGate {
  const body = [
    hashComment(header('azure-pipelines', 'file', 'yaml', invocationNote(model))),
    '#',
    '# Azure Pipelines binds a YAML file to a pipeline when the pipeline is created',
    '# in the web UI; unlike GitHub Actions it does not pick up new files on its own.',
    '# Creating that pipeline is the follow-up step, and until it is done this file',
    '# runs nowhere.',
    'trigger:',
    '  - main',
    '',
    'pr:',
    '  - main',
    '',
    'pool:',
    '  vmImage: ubuntu-latest',
    '',
    'steps:',
    indent(azureSteps(model).join('\n'), 2),
  ].join('\n');

  return {
    system: 'azure-pipelines',
    name: CI_SYSTEM_NAMES['azure-pipelines'],
    delivery: 'file',
    write: {
      path: join(repoRoot, 'azure-pipelines-checkyourvibe.yml'),
      strategy: 'managed-block',
      blockId: `${BLOCK_ID_PREFIX}azure-pipelines`,
      blockComment: 'hash',
      content: body,
      description:
        'Add a second Azure Pipelines YAML file holding the checkyourvibe gate, leaving azure-pipelines.yml untouched.',
    },
    snippet: body,
    manualReason: undefined,
    followUp: [
      'Create a pipeline in Azure DevOps pointing at azure-pipelines-checkyourvibe.yml. ' +
        'Azure binds YAML files to pipelines through its web UI, so a file alone runs nothing.',
    ],
  };
}

function circleSteps(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    switch (step.kind) {
      case 'checkout':
        lines.push('- checkout');
        break;
      case 'setup-node':
        // Expressed as the job's docker image, below.
        break;
      case 'enable-corepack':
        lines.push('- run:', '    name: Enable corepack', '    command: corepack enable');
        break;
      case 'install-dependencies':
        lines.push('- run:', '    name: Install dependencies', `    command: ${step.command}`);
        break;
      case 'run-gate':
        lines.push('- run:', '    name: checkyourvibe', '    command: |', indent(step.script, 6));
        break;
    }
  }

  return lines;
}

function renderCircleCi(model: GateModel): CiGate {
  const snippet = [
    hashComment(header('circleci', 'manual', 'yaml', invocationNote(model))),
    '',
    '# Under the existing top-level `jobs:` key:',
    'checkyourvibe:',
    '  docker:',
    '    # Adjust the tag if this project pins a specific Node version.',
    `    - image: cimg/node:${nodeVersionOf(model)}`,
    '  steps:',
    indent(circleSteps(model).join('\n'), 4),
    '',
    '# And under the workflow that should gate on it:',
    '#   - checkyourvibe',
  ].join('\n');

  return {
    system: 'circleci',
    name: CI_SYSTEM_NAMES.circleci,
    delivery: 'manual',
    write: undefined,
    snippet,
    manualReason:
      'CircleCI reads only .circleci/config.yml, and a job has to nest under that file\'s ' +
      'existing `jobs:` key and be named again in a workflow. A managed block appended at ' +
      'the top level would be an invalid config, not an added job, so nothing is written.',
    followUp: [
      'Paste the job under `jobs:` in .circleci/config.yml and add `- checkyourvibe` to the workflow that should gate on it.',
    ],
  };
}

function jenkinsSteps(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    switch (step.kind) {
      case 'checkout':
        lines.push('checkout scm');
        break;
      case 'setup-node':
        lines.push(`// Requires Node ${step.version} on the agent, or a nodejs tool block around these steps.`);
        break;
      case 'enable-corepack':
        lines.push("sh 'corepack enable'");
        break;
      case 'install-dependencies':
        lines.push(`sh '${step.command}'`);
        break;
      case 'run-gate':
        lines.push("sh '''", indent(step.script, 2), "'''");
        break;
    }
  }

  return lines;
}

function renderJenkins(model: GateModel): CiGate {
  const snippet = [
    slashComment(header('jenkins', 'manual', 'nothing', invocationNote(model))),
    '',
    '// Add inside the `stages { }` block of a declarative Jenkinsfile:',
    "stage('checkyourvibe') {",
    '  steps {',
    indent(jenkinsSteps(model).join('\n'), 4),
    '  }',
    '}',
  ].join('\n');

  return {
    system: 'jenkins',
    name: CI_SYSTEM_NAMES.jenkins,
    delivery: 'manual',
    write: undefined,
    snippet,
    manualReason:
      'A Jenkinsfile is Groovy with arbitrary control flow, and a stage has to land inside ' +
      'an existing `stages { }` block. Finding that insertion point means parsing Groovy, ' +
      'which this tool does not do, so the stage is printed rather than guessed into place.',
    followUp: ['Add the stage inside the `stages { }` block of your Jenkinsfile.'],
  };
}

function bitbucketSteps(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    switch (step.kind) {
      case 'checkout':
        // Bitbucket clones before the step runs; depth is a `clone:` key, below.
        break;
      case 'setup-node':
        // Expressed as the step's `image:`, below.
        break;
      case 'enable-corepack':
        lines.push('- corepack enable');
        break;
      case 'install-dependencies':
        lines.push(`- ${step.command}`);
        break;
      case 'run-gate':
        lines.push('- |', indent(step.script, 2));
        break;
    }
  }

  return lines;
}

function renderBitbucket(model: GateModel): CiGate {
  const snippet = [
    hashComment(header('bitbucket-pipelines', 'manual', 'yaml', invocationNote(model))),
    '',
    '# At the top level, so the clone is not shallow:',
    'clone:',
    `  depth: ${fetchDepthOf(model) === 0 ? 'full' : String(fetchDepthOf(model))}`,
    '',
    '# And as a step under the pipeline that should gate:',
    '- step:',
    '    name: checkyourvibe',
    `    image: node:${nodeVersionOf(model)}`,
    '    script:',
    indent(bitbucketSteps(model).join('\n'), 6),
  ].join('\n');

  return {
    system: 'bitbucket-pipelines',
    name: CI_SYSTEM_NAMES['bitbucket-pipelines'],
    delivery: 'manual',
    write: undefined,
    snippet,
    manualReason:
      'Bitbucket reads only bitbucket-pipelines.yml, and a step has to nest under the ' +
      '`pipelines:` key of whichever branch or pull-request pipeline should run it. There ' +
      'is no top-level position a managed block could occupy, so nothing is written.',
    followUp: [
      'Add the step under the `pipelines:` entry that should gate, and the `clone:` key at the top level.',
    ],
  };
}

function travisScript(model: GateModel): string[] {
  const lines: string[] = [];

  for (const step of model.steps) {
    switch (step.kind) {
      case 'checkout':
        // Travis clones before the job; depth is the `git: depth:` key, below.
        break;
      case 'setup-node':
        // Expressed as `node_js:`, below.
        break;
      case 'enable-corepack':
        lines.push('- corepack enable');
        break;
      case 'install-dependencies':
        lines.push(`- ${step.command}`);
        break;
      case 'run-gate':
        lines.push('- |', indent(step.script, 2));
        break;
    }
  }

  return lines;
}

function renderTravis(model: GateModel): CiGate {
  const snippet = [
    hashComment(header('travis-ci', 'manual', 'yaml', invocationNote(model))),
    '',
    '# At the top level, so the clone is not shallow:',
    'git:',
    '  depth: false',
    '',
    '# And as a job under `jobs: include:`:',
    '- name: checkyourvibe',
    '  language: node_js',
    `  node_js: '${nodeVersionOf(model)}'`,
    '  script:',
    indent(travisScript(model).join('\n'), 4),
  ].join('\n');

  return {
    system: 'travis-ci',
    name: CI_SYSTEM_NAMES['travis-ci'],
    delivery: 'manual',
    write: undefined,
    snippet,
    manualReason:
      'Travis reads only .travis.yml, and this job has to nest under `jobs: include:`. ' +
      'Appending it at the top level would collide with the keys already there, so nothing ' +
      'is written.',
    followUp: ['Add the job under `jobs: include:` in .travis.yml, and the `git: depth: false` key at the top level.'],
  };
}

/**
 * The gate for one detected system.
 *
 * Every branch is a call, so the `switch` is exhaustive over `CiSystemId` and a
 * new platform does not compile until it has a renderer.
 */
export function renderGate(system: CiSystemId, repoRoot: string, model: GateModel): CiGate {
  switch (system) {
    case 'github-actions':
      return renderGithubActions(repoRoot, model);
    case 'gitlab-ci':
      return renderGitlabCi(repoRoot, model);
    case 'azure-pipelines':
      return renderAzurePipelines(repoRoot, model);
    case 'circleci':
      return renderCircleCi(model);
    case 'jenkins':
      return renderJenkins(model);
    case 'bitbucket-pipelines':
      return renderBitbucket(model);
    case 'travis-ci':
      return renderTravis(model);
  }
}
