import {
  Node,
  type ts,
  type ArrowFunction,
  type CallExpression,
  type FunctionDeclaration,
  type FunctionExpression,
  type MethodDeclaration,
  type SourceFile,
  type Type,
  type TypeChecker,
  type TypeNode,
} from 'ts-morph';
import { makeViolation } from '../util.js';
import type { RuleManifest, Violation } from '@checkyourvibe/core';
import type { TsRule } from '../rule.js';

const RULE_ID = 'no-json-parse-cast';

const MESSAGE =
  'Parsing untrusted text produces a value whose actual shape is unknown at runtime; this code treats it as a specific, unchecked shape.';

// A function-like declaration or expression that can carry an explicit return
// type annotation. Named explicitly (rather than cast to) so the four `Node.isXxx`
// checks below stay a real narrowing, not an assertion about a shared shape.
type ReturnTypedFunctionLike = FunctionDeclaration | ArrowFunction | MethodDeclaration | FunctionExpression;

function isReturnTypedFunctionLike(node: Node): node is ReturnTypedFunctionLike {
  return (
    Node.isFunctionDeclaration(node) ||
    Node.isArrowFunction(node) ||
    Node.isMethodDeclaration(node) ||
    Node.isFunctionExpression(node)
  );
}

/**
 * Whether `type` is, or structurally contains, `any` or `unknown`.
 *
 * `seen` breaks cycles. A type can reach itself through its own union members
 * or type arguments — the JSON type generated by Supabase and written by hand
 * in plenty of codebases is the common case:
 *
 *   type Json = string | number | boolean | null | { [k: string]: Json } | Json[]
 *
 * Walking that without a guard recurs until the stack runs out. The analyzer
 * catches the throw and reports the rule as failed for that file, which does
 * not fail the run, so the file is quietly left unchecked while the summary
 * still reads as a clean pass. A type already on the path contributes nothing
 * new, so returning false for it is the answer, not just a way to terminate.
 */
function containsAnyOrUnknown(type: Type, seen: Set<ts.Type> = new Set()): boolean {
  if (type.isAny() || type.isUnknown()) {
    return true;
  }

  if (seen.has(type.compilerType)) {
    return false;
  }
  seen.add(type.compilerType);

  if (type.isArray() || type.isTuple()) {
    const elementType = type.getArrayElementType();
    if (elementType !== undefined && containsAnyOrUnknown(elementType, seen)) {
      return true;
    }
  }

  for (const arg of type.getTypeArguments()) {
    if (containsAnyOrUnknown(arg, seen)) {
      return true;
    }
  }

  if (type.isUnion()) {
    for (const unionType of type.getUnionTypes()) {
      if (containsAnyOrUnknown(unionType, seen)) {
        return true;
      }
    }
  }

  return false;
}

// `any` and `unknown` do not claim a specific shape, so they are outside this
// rule's scope. A missing type annotation also makes no claim.
function isUnshapedType(typeNode: TypeNode | undefined, typeChecker: TypeChecker): boolean {
  if (typeNode === undefined) {
    return true;
  }

  const type = typeChecker.getTypeAtLocation(typeNode);
  return containsAnyOrUnknown(type);
}

// The offending call may sit inside `await` or parentheses, e.g. `(await res.json()) as Config`.
function unwrapParseCall(node: Node | undefined, typeChecker: TypeChecker): CallExpression | undefined {
  if (node === undefined) {
    return undefined;
  }

  let current: Node = node;
  while (Node.isParenthesizedExpression(current) || Node.isAwaitExpression(current)) {
    current = current.getExpression();
  }

  if (!Node.isCallExpression(current)) {
    return undefined;
  }

  const callee = current.getExpression();
  if (!Node.isPropertyAccessExpression(callee)) {
    return undefined;
  }

  const name = callee.getName();
  if (name === 'json') {
    // Instance `.json()` calls on response or body objects read and parse JSON.
    // Static constructor `.json(...)` calls on a response class build a JSON response
    // instead, so they are not the same risk.
    const receiver = callee.getExpression();
    const receiverType = typeChecker.getTypeAtLocation(receiver);
    if (!receiverType.isAny() && !receiverType.isUnknown() && receiverType.getConstructSignatures().length > 0) {
      return undefined;
    }

    return current;
  }

  if (name === 'parse') {
    const receiver = callee.getExpression();
    if (Node.isIdentifier(receiver) && receiver.getText() === 'JSON') {
      return current;
    }
  }

  return undefined;
}

function getEnclosingReturnTypeNode(node: Node): TypeNode | undefined {
  const ancestor = node.getFirstAncestor(isReturnTypedFunctionLike);

  if (ancestor === undefined) {
    return undefined;
  }

  return ancestor.getReturnTypeNode();
}

const manifest: RuleManifest = {
  id: RULE_ID,
  category: 'type-safety',
  pack: 'strict-boundaries',
  scope: 'file',
  severity: 'error',
  evidence: 'syntax',
  summary: 'Do not treat the result of parsing untrusted text as a specific type without validating it first.',
  why:
    'A parser converts raw text into a runtime value, but the text may not contain the fields, types, or structure the code expects. ' +
    'Annotating, casting, or returning that value as a concrete type tells the compiler to trust a shape that has never been checked. ' +
    'The mismatch then surfaces as a runtime failure or a silently wrong value instead of a compile-time error.',
  allowedFixes: [
    'Validate at the boundary with a runtime schema validator and use the validated result\'s inferred type.',
    'Hand-write a type-guard predicate that actually inspects the fields before using the value.',
    'Keep the parsed value as `unknown` and narrow it at each use site with `typeof`, `instanceof`, or `in` checks.',
  ],
  notFixes: [
    {
      pattern: 'Route the parse result through `unknown` first, then cast to the target type.',
      because:
        'The value still reaches the target type without a runtime check; the indirection does not validate the shape.',
    },
    {
      pattern: 'Cast the parsed value with `as` or angle brackets.',
      rule: 'no-as-cast',
      because:
        'A cast asserts a type without proof, so the untrusted value can still have the wrong shape at runtime.',
    },
    {
      pattern: 'Assert that parsed fields or the whole object are non-null with `!`.',
      rule: 'no-non-null-assertion',
      because:
        'After parsing, the data may be missing fields; `!` asserts they exist without checking, which is the same unchecked claim moved to a different operator.',
    },
    {
      pattern: 'Type the result as `any` so no assertion is needed.',
      rule: 'no-any',
      because:
        'Widening to `any` removes the type claim but also removes type checking entirely, which is a broader violation.',
    },
    {
      pattern: 'Suppress the resulting error with a compiler-directive comment.',
      rule: 'no-ts-comment',
      because:
        'A directive comment hides the type error without validating the value, so the runtime risk remains.',
    },
  ],
  examples: {
    bad: `const config1 = JSON.parse(raw) as Config;
const config2 = <Config>JSON.parse(raw);
const config3: Config = JSON.parse(raw);
function getConfig(): Config { return JSON.parse(raw); }
const config4 = (await res.json()) as Config;`,
    good: `const raw = JSON.parse(text);

function isConfig(value: unknown): value is Config {
  return typeof value === 'object' && value !== null && 'name' in value;
}

const parsed = JSON.parse(text);
if (isConfig(parsed)) {
  console.log(parsed.name);
}

const untyped: unknown = JSON.parse(text);
if (typeof untyped === 'object' && untyped !== null && 'name' in untyped) {
  const record = untyped as Record<string, unknown>;
  if (typeof record.name === 'string') {
    console.log(record.name);
  }
}`,
  },
};

function check(sourceFile: SourceFile, _options: Record<string, unknown>): Violation[] {
  const violations: Violation[] = [];
  const typeChecker = sourceFile.getProject().getTypeChecker();

  // Report the outermost claim node for each parse call to avoid duplicate violations.
  for (const node of sourceFile.getDescendants()) {
    if (Node.isAsExpression(node) || Node.isTypeAssertion(node)) {
      const typeNode = node.getTypeNode();
      if (!isUnshapedType(typeNode, typeChecker) && unwrapParseCall(node.getExpression(), typeChecker) !== undefined) {
        violations.push(makeViolation(sourceFile, node, RULE_ID, MESSAGE, 'error'));
      }
      continue;
    }

    if (Node.isVariableDeclaration(node)) {
      const typeNode = node.getTypeNode();
      const initializer = node.getInitializer();
      if (typeNode !== undefined && !isUnshapedType(typeNode, typeChecker) && unwrapParseCall(initializer, typeChecker) !== undefined) {
        violations.push(makeViolation(sourceFile, node, RULE_ID, MESSAGE, 'error'));
      }
      continue;
    }

    if (Node.isReturnStatement(node)) {
      const returnTypeNode = getEnclosingReturnTypeNode(node);
      if (!isUnshapedType(returnTypeNode, typeChecker) && unwrapParseCall(node.getExpression(), typeChecker) !== undefined) {
        violations.push(makeViolation(sourceFile, node, RULE_ID, MESSAGE, 'error'));
      }
      continue;
    }

    if (Node.isArrowFunction(node)) {
      const returnTypeNode = node.getReturnTypeNode();
      const body = node.getBody();
      if (
        returnTypeNode !== undefined &&
        !isUnshapedType(returnTypeNode, typeChecker) &&
        !Node.isBlock(body) &&
        unwrapParseCall(body, typeChecker) !== undefined
      ) {
        violations.push(makeViolation(sourceFile, node, RULE_ID, MESSAGE, 'error'));
      }
    }
  }

  return violations;
}

export const noJsonParseCast: TsRule = { manifest, check };
